/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IFarm } from "./IFarm";

export class IFarmFactory {
  static connect(address: string, signerOrProvider: Signer | Provider): IFarm {
    return new Contract(address, _abi, signerOrProvider) as IFarm;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pid",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "userInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "rewardDebt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "bonusDebt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "fundedBy",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
