/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IHarvestInfoInterface extends ethers.utils.Interface {
  functions: {
    "pending(address)": FunctionFragment;
    "pendingDollarValue(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "pending", values: [string]): string;
  encodeFunctionData(
    functionFragment: "pendingDollarValue",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "pending", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingDollarValue",
    data: BytesLike
  ): Result;

  events: {};
}

export class IHarvestInfo extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IHarvestInfoInterface;

  functions: {
    pending(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "pending(address)"(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    pendingDollarValue(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "pendingDollarValue(address)"(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  pending(_strategy: string, overrides?: CallOverrides): Promise<BigNumber>;

  "pending(address)"(
    _strategy: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  pendingDollarValue(
    _strategy: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "pendingDollarValue(address)"(
    _strategy: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    pending(_strategy: string, overrides?: CallOverrides): Promise<BigNumber>;

    "pending(address)"(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingDollarValue(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pendingDollarValue(address)"(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    pending(_strategy: string, overrides?: CallOverrides): Promise<BigNumber>;

    "pending(address)"(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingDollarValue(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pendingDollarValue(address)"(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    pending(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pending(address)"(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingDollarValue(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pendingDollarValue(address)"(
      _strategy: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
