/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IVaultInterface extends ethers.utils.Interface {
  functions: {
    "deposit(uint256)": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {};
}

export class IVault extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IVaultInterface;

  functions: {
    deposit(
      amountToken: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "deposit(uint256)"(
      amountToken: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    withdraw(
      share: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "withdraw(uint256)"(
      share: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  deposit(
    amountToken: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "deposit(uint256)"(
    amountToken: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  withdraw(
    share: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "withdraw(uint256)"(
    share: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    deposit(
      amountToken: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "deposit(uint256)"(
      amountToken: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(share: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "withdraw(uint256)"(
      share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    deposit(
      amountToken: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "deposit(uint256)"(
      amountToken: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    withdraw(
      share: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "withdraw(uint256)"(
      share: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deposit(
      amountToken: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "deposit(uint256)"(
      amountToken: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      share: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "withdraw(uint256)"(
      share: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
